name: .NET Build IR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test Dapper

    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

      # Setup .NET SDK
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11

      # Restore dependencies using the solution
      - name: Restore dependencies
        run: dotnet restore Dapper.sln

      # Build all projects in the solution
      - name: Build (skip analyzers)
        run: dotnet build Dapper.sln --no-restore /p:RunAnalyzers=false

      # Run tests for all test projects
      - name: Test
        run: dotnet test Dapper.sln --no-build --verbosity normal
