name: .NET Build IR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          tags: true

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.100-rc.2.24474.11

      - name: Restore dependencies
        run: dotnet restore Dapper.sln

      - name: Build (skip analyzers)
        run: dotnet build Dapper.sln --no-restore /p:RunAnalyzers=false

      - name: Test
        run: dotnet test Dapper.sln --no-build --verbosity normal
